### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#170]
You've hard coded the build tools paths :(

https://f-droid.org/wiki/index.php?title=org.atalk.android/lastbuild_1144&oldid=283988

I've tried to fix the recipe, but it's not done yet
```
  - versionName: 2.4.4
    versionCode: 1144
    commit: 2.4.4
    subdir: aTalk/
    patch:
      - build.patch
    gradle:
      - fdroid
    srclibs:
      - fmj@r122
      - jitsi-zrtp4j@7cbd8101108191089aad871002567c2a0eb2b512
    rm:
      - aTalk/lib/src_reference/
      - aTalk/jni/ffmpeg/android/
      - aTalk/jni/openssl/android/
      - aTalk/jni/vpx/android/
    prebuild:
      - sed -i -e "/clean.dependsOn 'ndkClean'/d" -e 's:/opt/android/android-sdk/ndk/20.0.5594570:$$NDK$$:'
        -e 's/20.0.5594570/20.1.5948944/' build.gradle
      - sed -i -e 's/STANDALONE_TOOLCHAINS=1;/STANDALONE_TOOLCHAINS=0;/' jni/static_library_built/ffmpeg-x264/_settings.sh
    scanignore:
      - aTalk/build.gradle
    scandelete:
      - aTalk/jni/static_library_built/libvpx/sources/*.gz
      - aTalk/third_party/m2/org/igniterealtime/smack/*/*/*.jar
    build:
      - export PATH=$$NDK$$/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
      - pushd $$fmj$$
      - ant
      - popd
      - pushd $$jitsi-zrtp4j$$
      - ant jar
      - popd
      - mkdir -p lib/bundles
      - mv $$fmj$$/build/jars/fmj.jar lib/bundles/fmj-1.0-SNAPSHOT.jar
      - mv $$jitsi-zrtp4j$$/dist/zrtp4j-light.jar lib/bundles/zrtp4j-light-4.1.0-jitsi-1-SNAPSHOT.jar
      - pushd jni/static_library_built/ffmpeg-x264/
      - ./init_update_libs.sh
      - ./ffmpeg-atalk_build.sh
      - popd
      - mv jni/static_library_built/ffmpeg-x264/android/ jni/ffmpeg/
      - pushd jni/static_library_built/libvpx/
      - ./init_libvpx.sh
      - ./build-libvpx4android.sh
      - popd
      - mv jni/static_library_built/libvpx/output/android/ jni/vpx/
      - pushd jni/static_library_built/openssl/
      - ./init_libopenssl.sh
      - ./build-openssl4android.sh
      - popd
      - mv jni/static_library_built/openssl/output/android/ jni/openssl/
    ndk: r20b
```

build.patch
```
--- a/aTalk/jni/static_library_built/ffmpeg-x264/_settings.sh
+++ b/aTalk/jni/static_library_built/ffmpeg-x264/_settings.sh
@@ -30,9 +30,6 @@
 ANDROID_API=21
 NDK_ABI_VERSION=4.9

-# set STANDALONE_TOOLCHAINS to 0: SDK toolchains OR 1: standalone toolchains
-STANDALONE_TOOLCHAINS=1;
-
 # Built with command i.e. ./ffmpeg-android_build.sh or following with parameter [ABIS(x)]
 # Create custom ABIS or uncomment to build all supported abi for ffmpeg.
 # Do not change naming convention of the ABIS; see:
@@ -41,10 +38,6 @@
 ABIS=("armeabi-v7a" "arm64-v8a" "x86" "x86_64")

 BASEDIR=`pwd`
-# need to define earlier for standalone toolchains option
-# if [[ STANDALONE_TOOLCHAINS == 1 ]]; then
-#   TOOLCHAIN_PREFIX=${BASEDIR}/toolchain-android
-# fi

 #===========================================
 # Do not proceed further on first call without the required 2 parameters
@@ -130,37 +123,16 @@
   ;;
 esac

-if [[ ${STANDALONE_TOOLCHAINS} == 1 ]]; then
-  TOOLCHAIN_PREFIX=${BASEDIR}/toolchain-android
-  NDK_SYSROOT=${TOOLCHAIN_PREFIX}/sysroot
-  CC_=clang
-  CXX_=clang++
-
-  if [[ ! -e ${TOOLCHAIN_PREFIX}/${NDK_ABIARCH} ]]; then
-    rm -rf ${TOOLCHAIN_PREFIX}
-
-    # Create standalone toolchains for the specified architecture - use .py instead of the old .sh
-  # However for ndk--r19b => Instead use:
-  #    $ ${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ src.cpp
-  # cmeng: must ensure AS JNI uses the same STL library or "system" if specified
-    [[ -d ${TOOLCHAIN_PREFIX} ]] || python ${NDK}/build/tools/make_standalone_toolchain.py \
-      --arch ${NDK_ARCH} \
-      --api ${ANDROID_API} \
-      --stl libc++ \
-      --install-dir=${TOOLCHAIN_PREFIX}
-  fi
-else
-  TOOLCHAIN_PREFIX=${ANDROID_NDK}/toolchains/${NDK_ABIARCH}-${NDK_ABI_VERSION}/prebuilt/linux-x86_64
-  NDK_SYSROOT=${ANDROID_NDK}/platforms/android-${ANDROID_API}/arch-${NDK_ARCH}
-  CC_=gcc
-  CXX_=g++
-fi
+CC_=clang
+CXX_=clang++
+TOOLCHAIN_PREFIX=${ANDROID_NDK}/toolchains/${NDK_ABIARCH}-${NDK_ABI_VERSION}/prebuilt/linux-x86_64
+NDK_SYSROOT=${ANDROID_NDK}/platforms/android-${ANDROID_API}/arch-${NDK_ARCH}

 # Define the install directory of the libs and include files etc
 # lame needs absolute path
 PREFIX=${BASEDIR}/android/$1

-# Add the standalone toolchain to the search path.
+# Add the [5~standalone toolchain to the search path.
 export PATH=${TOOLCHAIN_PREFIX}/bin:$PATH
 export CROSS_PREFIX=${TOOLCHAIN_PREFIX}/bin/${NDK_ABIARCH}-
 export CFLAGS="${CFLAGS}"
```
